#backup:
#  container_name: backup
#  build: docker/backup
wwwdata:
  container_name: wwwdata
  build: wwwdata
nginx:
  container_name: nginx
  build: nginx
php56:
  container_name: php56
  build: php56
php70:
  container_name: php70
  build: php70
#mariadb:
#  container_name: mariadb
#  build: mariadb
#memcached:
#  container_name: memcached
#  build: memcached
#redis:
#  container_name: redis
#  build: redis
#mail:
#  container_name: mail
#  build: postfix